name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/lxpio/epubx.dart
issue_tracker: https://github.com/lxpio/epubx.dart
version: 4.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  path: ^1.9.0
  xml: ^6.0.1
  image: ^4.1.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.25.0
  path: ^1.9.0
  pedantic: ^1.11.0
